start "Network Cable Cloud" "TESTBAT\NetworkCableCloud.exe"
start "Network Node 1" "TESTBAT\NetworkNode.exe"
start "Network Node 2" "TESTBAT\NetworkNode.exe"
start "Network Node 3" "TESTBAT\NetworkNode.exe"
start "Network Node 4" "TESTBAT\NetworkNode.exe"
start "Network Node 5" "TESTBAT\NetworkNode.exe"
start "Network Node 6" "TESTBAT\NetworkNode.exe"
start "Network Node 7" "TESTBAT\NetworkNode.exe"
start "SubNetwork 1" "TESTBAT\SubNetwork.exe"
start "SubNetwork 2" "TESTBAT\SubNetwork.exe"
